<a href="https://colab.research.google.com/github/Mjdiazri/Code7Days/blob/main/Ejercicio_promt_python_dataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Acceso a los datos**

A continuacion se presentara dos opciones para acceder a los datos:
Opcion 1: Utilizar la funcion pd.read_json para crear el dataframe
Opcion 2: Realizar el acceso desde la api y crear dataframe con request y funcion pd.Dataframe

In [1]:
#busca recolectar y acceder a los datos del archivo que están en formato JSON. Es importante dejar todos los datos de manera accesible, evitando estructuras que recuerden a un archivo JSON, como diccionarios.

#Opcion 1: Con url fija
url_franquicias = 'https://gist.githubusercontent.com/ahcamachod/68eede222bdf1ba0ca413d529e800e7c/raw/576b0f3856467817df0fcf041d4a0787579917b0/ventas_franquicia.json'

In [2]:
import pandas as pd
import numpy as np

In [ ]:
#busca recolectar y acceder a los datos del archivo que están en formato JSON. Es importante dejar todos los datos de manera accesible, evitando estructuras que recuerden a un archivo JSON, como diccionarios.

#Opcion 2: Desde api

import requests

#Solicitud a la api
response = requests.get(url_franquicias)
#Convirtiendo respuesta de json a objeto python
data = response.json()
#Creando dataframe
datafra= pd.DataFrame(data)
datafra

,ID_tienda,ventas,tienda
0,OUT431,"{'ventas_por_dia': None, 'ventas_tienda': 8222...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
1,OUT738,"{'ventas_por_dia': None, 'ventas_tienda': 1032...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
2,OUT426,"{'ventas_por_dia': None, 'ventas_tienda': 5548...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
3,OUT948,"{'ventas_por_dia': None, 'ventas_tienda': 9641...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
4,OUT139,"{'ventas_por_dia': None, 'ventas_tienda': 5680...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
...,...,...,...
893,OUT206,"{'ventas_por_dia': None, 'ventas_tienda': 8787...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
894,OUT370,"{'ventas_por_dia': None, 'ventas_tienda': 2941...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
895,OUT960,"{'ventas_por_dia': None, 'ventas_tienda': 5736...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
896,OUT535,"{'ventas_por_dia': None, 'ventas_tienda': 6158...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
897,OUT202,"{'ventas_por_dia': None, 'ventas_tienda': 9541...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."

In [3]:
#Continuacion proceso, igual dos opciones

uf = pd.read_json(url_franquicias)
uf

,ID_tienda,ventas,tienda
0,OUT431,"{'ventas_por_dia': None, 'ventas_tienda': 8222...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
1,OUT738,"{'ventas_por_dia': None, 'ventas_tienda': 1032...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
2,OUT426,"{'ventas_por_dia': None, 'ventas_tienda': 5548...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
3,OUT948,"{'ventas_por_dia': None, 'ventas_tienda': 9641...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
4,OUT139,"{'ventas_por_dia': None, 'ventas_tienda': 5680...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
...,...,...,...
893,OUT206,"{'ventas_por_dia': None, 'ventas_tienda': 8787...","{'tamano_tienda': 'medio', 'cliente_por_dia': ..."
894,OUT370,"{'ventas_por_dia': None, 'ventas_tienda': 2941...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
895,OUT960,"{'ventas_por_dia': None, 'ventas_tienda': 5736...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."
896,OUT535,"{'ventas_por_dia': None, 'ventas_tienda': 6158...","{'tamano_tienda': 'pequeno', 'cliente_por_dia'..."
897,OUT202,"{'ventas_por_dia': None, 'ventas_tienda': 9541...","{'tamano_tienda': 'Pequeno', 'cliente_por_dia'..."

In [4]:
#Se tienen dos diccionarios: ventas y tienda

#Normalizacion Ventas
ventas_uf= pd.json_normalize(uf['ventas'])
ventas_uf

     ventas_por_dia  ventas_tienda
0               NaN   82220.053714
1               NaN  103231.728424
2               NaN   55487.996318
3               NaN   96417.999686
4               NaN   56809.025487
..              ...            ...
893             NaN   87875.440154
894             NaN   29410.047183
895             NaN   57362.867709
896             NaN   61585.737092
897             NaN   95416.455607

[898 rows x 2 columns]

In [5]:
#Normalizacion tienda

tienda_uf = pd.json_normalize(uf['tienda'])
tienda_uf

    tamano_tienda  cliente_por_dia  items_disponibles
0         pequeno            330.0               1968
1           medio            310.0               2189
2         pequeno            870.0               1736
3         Pequeno           1560.0               1099
4         Pequeno             10.0               1516
..            ...              ...                ...
893         medio            810.0               2031
894       Pequeno            780.0               1439
895       Pequeno            660.0               1510
896       pequeno            990.0               1836
897       Pequeno           1170.0               1500

[898 rows x 3 columns]

In [6]:
#Unificacion dataframe

uf_union = pd.concat([uf.drop(['ventas', 'tienda'],axis=1), ventas_uf, tienda_uf], axis=1)

In [ ]:
uf_union

,ID_tienda,ventas_por_dia,ventas_tienda,tamano_tienda,cliente_por_dia,items_disponibles
0,OUT431,NaN,82220.053714,pequeno,330.0,1968
1,OUT738,NaN,103231.728424,medio,310.0,2189
2,OUT426,NaN,55487.996318,pequeno,870.0,1736
3,OUT948,NaN,96417.999686,Pequeno,1560.0,1099
4,OUT139,NaN,56809.025487,Pequeno,10.0,1516
...,...,...,...,...,...,...
893,OUT206,NaN,87875.440154,medio,810.0,2031
894,OUT370,NaN,29410.047183,Pequeno,780.0,1439
895,OUT960,NaN,57362.867709,Pequeno,660.0,1510
896,OUT535,NaN,61585.737092,pequeno,990.0,1836
897,OUT202,NaN,95416.455607,Pequeno,1170.0,1500

**Exploracion del dataframe**

In [ ]:
uf_union.head()

,ID_tienda,ventas_por_dia,ventas_tienda,tamano_tienda,cliente_por_dia,items_disponibles
0,OUT431,NaN,82220.053714,pequeno,330.0,1968
1,OUT738,NaN,103231.728424,medio,310.0,2189
2,OUT426,NaN,55487.996318,pequeno,870.0,1736
3,OUT948,NaN,96417.999686,Pequeno,1560.0,1099
4,OUT139,NaN,56809.025487,Pequeno,10.0,1516

In [ ]:
uf_union.tail()

,ID_tienda,ventas_por_dia,ventas_tienda,tamano_tienda,cliente_por_dia,items_disponibles
893,OUT206,NaN,87875.440154,medio,810.0,2031
894,OUT370,NaN,29410.047183,Pequeno,780.0,1439
895,OUT960,NaN,57362.867709,Pequeno,660.0,1510
896,OUT535,NaN,61585.737092,pequeno,990.0,1836
897,OUT202,NaN,95416.455607,Pequeno,1170.0,1500

In [ ]:
uf_union.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_tienda          898 non-null    object
 1   ventas_por_dia     1 non-null      float64
 2   ventas_tienda      898 non-null    float64
 3   tamano_tienda      878 non-null    object
 4   cliente_por_dia    880 non-null    float64
 5   items_disponibles  898 non-null    int64
dtypes: float64(3), int64(1), object(2)
memory usage: 42.2+ KB

In [ ]:
uf_union.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_tienda          898 non-null    object
 1   ventas_por_dia     1 non-null      float64
 2   ventas_tienda      898 non-null    float64
 3   tamano_tienda      878 non-null    object
 4   cliente_por_dia    880 non-null    float64
 5   items_disponibles  898 non-null    int64
dtypes: float64(3), int64(1), object(2)
memory usage: 138.4 KB

In [ ]:
uf_union.describe()

       ventas_por_dia  ventas_tienda  cliente_por_dia  items_disponibles
count         1.00000     898.000000       880.000000         898.000000
mean       4294.64706   71071.894236       786.443182        1781.561247
std               NaN   22143.481947       267.038209         299.716498
min        4294.64706   19371.958539        10.000000         932.000000
25%        4294.64706   54510.922957       600.000000        1574.500000
50%        4294.64706   69228.128375       780.000000        1773.000000
75%        4294.64706   86119.754844       970.000000        1982.000000
max        4294.64706  152897.262005      1560.000000        2667.000000

In [ ]:
uf_union.shape

(898, 6)

In [ ]:
uf_union.isnull().sum()

ID_tienda              0
ventas_por_dia       897
ventas_tienda          0
tamano_tienda         20
cliente_por_dia       18
items_disponibles      0
dtype: int64

In [ ]:
#Valores duplicados por fila
uf_union.duplicated().sum()

np.int64(2)

In [ ]:
uf_union.nunique()

ID_tienda            896
ventas_por_dia         1
ventas_tienda        896
tamano_tienda          3
cliente_por_dia      130
items_disponibles    616
dtype: int64

In [ ]:
#Categorias unicas en columnas

uf_union['tamano_tienda'].unique()

array(['pequeno', 'medio', 'Pequeno', None], dtype=object)

In [ ]:
uf_union['items_disponibles'].unique()

array([1968, 2189, 1736, 1099, 1516, 2157, 1683, 1973, 2055, 1972, 1905,
       1370, 1546, 2053, 1783, 1844, 2024, 2065, 1436, 1382, 2420, 2015,
       1770, 1840, 1773, 1952, 1746, 1751, 1561, 2264, 1789, 2042, 1656,
       1857, 1635, 1752, 1808, 1418, 1699, 1727, 1125, 1584, 1858, 1670,
       2342, 1681, 1897, 1572, 1447, 1759, 2145, 1468, 1730, 2073, 1831,
       2019, 1885, 1807, 1194, 1605, 1630, 1648, 1487, 1791, 1606, 1073,
       1805, 1634, 1716, 1877, 1806, 1372, 1843, 2133, 2174, 1925, 1936,
       1338, 1753, 2390, 2262, 2208, 1832, 1342, 1909, 2061, 1774, 1515,
       1133, 1839, 1503, 1946, 1520, 1093, 2110, 1586, 1492, 1428, 1353,
       1322, 1622, 1692, 1958, 1959, 1678, 1947, 1872, 1559, 1480, 1523,
       2108, 1625, 2235, 1933, 1749, 2233, 1517, 1737, 2044, 1548, 1455,
       2008, 1412, 1406, 1574, 2095, 2052, 1660, 1489, 1659, 2046, 2244,
       1743, 1688, 1430, 2109, 1871, 1937, 1663, 1999, 2245, 2163, 1508,
       1775, 1948, 1462, 1700, 1475, 1229, 1557, 1723, 1825, 1733, 2153,
       1493, 2167, 1898, 1768, 1429, 1437, 2171, 2252, 2017, 1393, 1798,
       1525, 1439, 1473, 1616, 1661, 1589, 1404, 2131, 2071, 1701, 1836,
       1351, 1837, 1426, 2123, 1472, 2236, 2368, 1519, 2023, 1910, 1920,
       1511, 1939, 1883, 1154, 1087, 2396, 2064, 1704, 1906, 1264, 1507,
       1569, 1734, 1571, 1375, 2294, 1371, 1558, 1879, 1288, 1822, 1411,
       1813, 1609, 1819, 1954,  932, 1788, 1760, 1536, 1687, 1869, 1893,
       1719, 1724, 1398, 1988, 2137, 1761, 1918, 2045, 1464, 1860, 2400,
       1497, 1757, 1673, 1764, 1401, 1803, 1207, 2009, 1957, 2214, 1912,
       1413, 1396, 1332, 1715, 1576, 1270, 2493, 1993, 2176, 1943, 2115,
       1747, 1477, 2374, 1467, 1762, 1658, 1742, 2338, 1799, 1672, 2142,
       1717, 1152, 1050, 1878, 1662, 2060, 2147, 2076, 1488, 1686, 2101,
       1880, 1587, 1604, 2000, 1397, 1279, 1718, 1610, 1731, 2121, 2204,
       1884, 2391, 1215, 2339, 1262, 2185, 2146, 1722, 1308, 1481, 1848,
       1720, 1776, 2474, 2097, 1713, 1833, 1927, 1421, 2287, 1445, 2205,
       1601, 1758, 1583, 1986, 1892, 1725, 1420, 2305, 2098, 1638, 2117,
       2001, 1785, 1823, 2032, 1476, 1902, 2408, 1944, 1881, 1231, 2304,
       2278, 1802, 1950, 1748, 2280, 2003, 2154, 2020, 1527, 1928, 1645,
       1981, 1235, 1976, 2134, 1922, 1540, 1777, 2290, 1919, 2037, 1192,
       1505, 1655, 2111, 1766, 2038, 2216, 2173, 2002, 1963, 1956, 1366,
       1842, 1941, 2492, 2220, 1299, 1374, 1434, 1771, 2364, 2247, 1961,
       1708, 1829, 1633, 2241, 2197, 1529, 1379, 1595, 1680, 1623, 1817,
       1967, 1276, 1459, 1894, 2112, 1456, 1654, 1755, 1889, 1707, 2087,
       2228, 1305, 1121, 2034, 1106, 2215, 2311, 1452, 2070, 2138, 2254,
       1461, 1321, 1570, 1388, 2078, 1555, 1765, 1314, 1763,  951, 2300,
       1390, 1793, 1820, 1709, 1636, 2340, 1815, 2248, 1512, 1619, 1018,
       1306, 1896, 1347, 1845, 2051, 1735, 1931, 1649, 1482, 1916, 1446,
       2016, 2187, 1471, 1696, 1278, 1907, 1490, 1732, 2084, 2384, 2132,
       1646, 2186, 2175, 2362, 1369, 2195, 2343, 2436, 1854, 2086, 1982,
       1378, 2104, 1728, 2246, 1810, 1855, 2126, 1787, 2227, 1405, 1710,
       1930, 2240, 1677, 1506, 1591, 1744, 1291, 1739, 2184, 1612, 1433,
       1804, 1352, 1629, 1280, 2465, 1466, 1486, 1750, 2414, 1745, 1796,
       2333, 1876, 1945, 1827, 1608, 2056, 1669, 1579, 1539, 1911, 1120,
       1331, 1962, 2072, 1296, 1284, 1979, 1697, 2058, 2030, 1309, 1491,
       1440, 1499, 1246, 2010, 2306, 1643, 1924, 1484, 1794, 1650, 1216,
       2394, 1888, 1852, 1790, 2310, 1690, 1846, 1895, 1337, 1800, 1138,
       1886, 1861, 1534, 1384, 2230, 2647, 1599, 1387, 1345, 2385, 1821,
       1853, 1502, 1381, 1841, 1442, 2014, 1938, 1711, 1059, 2284, 1628,
       1838, 1674, 1530, 1202, 1422, 1417, 1590, 2222, 1756, 1921, 2026,
       1985, 1899, 2160, 1795, 1581, 1237, 1940, 1598, 1560, 1657, 1729,
       1689, 1386, 1562, 2277, 2158, 2149, 2617, 1172, 2378, 1554, 1801,
       1901, 1851, 1597, 1607, 1179, 2397, 1703, 2092, 2022, 1460, 1668,
       2148, 1695, 2349, 2048, 1273, 2667, 1835, 1380, 2031, 1510, 1500])

In [ ]:
# Verifica la cuenta de valores en una columna específica, por ejemplo, 'cliente_por_dia'
uf_union['cliente_por_dia'].value_counts()

cliente_por_dia
670.0     19
760.0     17
790.0     16
660.0     15
620.0     15
          ..
1530.0     1
70.0       1
130.0      1
1400.0     1
120.0      1
Name: count, Length: 130, dtype: int64

In [ ]:
# Estadísticas para la columna 'ventas_tienda'
uf_union['ventas_tienda'].agg(['min', 'max', 'mean', 'median', 'std'])

min        19371.958539
max       152897.262005
mean       71071.894236
median     69228.128375
std        22143.481947
Name: ventas_tienda, dtype: float64

**Limpieza de datos**

In [7]:
#Considerando que la columna ventas_por_dia	tiene 897/898 registros nulos se opta por eliminar

uf_union = uf_union.drop(columns=['ventas_por_dia'])

In [8]:
#Se tienen dos valores duplicados por fila

uf_union.duplicated().sum()

np.int64(2)

In [9]:
#Para validar que hacer con estos valores se revisa sus valores

uf_union[uf_union.duplicated()] #Solo muestra la primeras filas de las que estan duplicadas

    ID_tienda  ventas_tienda tamano_tienda  cliente_por_dia  items_disponibles
174    OUT139   56809.025487       Pequeno             10.0               1516
493    OUT392   53560.914249       pequeno            560.0               1622

In [10]:
#Validar todas las celdas duplicadas
duplicados = uf_union[uf_union.duplicated(keep=False)]
print(duplicados)

    ID_tienda  ventas_tienda tamano_tienda  cliente_por_dia  items_disponibles
4      OUT139   56809.025487       Pequeno             10.0               1516
102    OUT392   53560.914249       pequeno            560.0               1622
174    OUT139   56809.025487       Pequeno             10.0               1516
493    OUT392   53560.914249       pequeno            560.0               1622

In [11]:
#Se opta por eliminar los duplicados

uf_union = uf_union.drop_duplicates()

In [12]:
#Comprobacion
uf_union.duplicated().sum()

np.int64(0)

In [13]:
#Ya que se tiene en la columna tamano_tienda	20 registros nulos, se intentara validar los registros para confirmar si se pueden normalizar

uf_union[['tamano_tienda','ID_tienda']]

    tamano_tienda ID_tienda
0         pequeno    OUT431
1           medio    OUT738
2         pequeno    OUT426
3         Pequeno    OUT948
4         Pequeno    OUT139
..            ...       ...
893         medio    OUT206
894       Pequeno    OUT370
895       Pequeno    OUT960
896       pequeno    OUT535
897       Pequeno    OUT202

[896 rows x 2 columns]

In [14]:
#Muestra las columnas de ID y tamano, donde los valores son nulos
uf_union[uf_union['tamano_tienda'].isnull()][['ID_tienda','tamano_tienda']]

    ID_tienda tamano_tienda
20     OUT898          None
32     OUT396          None
39     OUT843          None
64     OUT296          None
183    OUT488          None
186    OUT414          None
235    OUT258          None
240    OUT706          None
242    OUT533          None
260    OUT233          None
306    OUT735          None
443    OUT949          None
539    OUT642          None
540    OUT117          None
602    OUT326          None
722    OUT185          None
784    OUT114          None
803    OUT555          None
827    OUT466          None
838    OUT373          None

In [15]:
#Mediante un sondeo se valida que los ID de estas tiendas son registros unicos
uf_union[uf_union['ID_tienda']== 'OUT642'][['ID_tienda','tamano_tienda']]

    ID_tienda tamano_tienda
539    OUT642          None

In [16]:
#Dada esta situacion, se opta por agregar nueva categoria de 'desconocido

uf_union['tamano_tienda'] = uf_union['tamano_tienda'].fillna('desconocido')

In [17]:
#Finalmente, la columna cliente_por_dia	tiene 18 registro nulos. Se opta por llenarlos con el promedio

uf_union['cliente_por_dia']= uf_union['cliente_por_dia'].fillna(uf_union['cliente_por_dia'].mean())

In [18]:
#Comprobacion

uf_union.isnull().sum()

ID_tienda            0
ventas_tienda        0
tamano_tienda        0
cliente_por_dia      0
items_disponibles    0
dtype: int64

In [22]:
# Con respecto a las diferentes categorias de la columna 'tamano_tienda' (pequeno', 'medio', 'Pequeno')se normaliza con funcion replace

uf_union['tamano_tienda'].replace({'pequeno': 'Pequeño', 'Pequeno':'Pequeño','medio':'Medio', 'desconocido': 'Desconocido'}, inplace=True)

<ipython-input-22-b9759cd119d5>:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  uf_union['tamano_tienda'].replace({'pequeno': 'Pequeño', 'Pequeno':'Pequeño','medio':'Medio', 'desconocido': 'Desconocido'}, inplace=True)

In [23]:
#Comprobacion
uf_union['tamano_tienda'].unique()

array(['Pequeño', 'Medio', 'Desconocido'], dtype=object)

In [24]:
# El siguiente ajuste es en la columna cliente_por_dia que registra como float pero los datos son int. Se cambia formato a int

uf_union['cliente_por_dia'] = uf_union['cliente_por_dia'].astype(int)

In [25]:
#Comprobacion

uf_union.info()

<class 'pandas.core.frame.DataFrame'>
Index: 896 entries, 0 to 897
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ID_tienda          896 non-null    object
 1   ventas_tienda      896 non-null    float64
 2   tamano_tienda      896 non-null    object
 3   cliente_por_dia    896 non-null    int64
 4   items_disponibles  896 non-null    int64
dtypes: float64(1), int64(2), object(2)
memory usage: 42.0+ KB

In [26]:
uf_union

    ID_tienda  ventas_tienda tamano_tienda  cliente_por_dia  items_disponibles
0      OUT431   82220.053714       Pequeño              330               1968
1      OUT738  103231.728424         Medio              310               2189
2      OUT426   55487.996318       Pequeño              870               1736
3      OUT948   96417.999686       Pequeño             1560               1099
4      OUT139   56809.025487       Pequeño               10               1516
..        ...            ...           ...              ...                ...
893    OUT206   87875.440154         Medio              810               2031
894    OUT370   29410.047183       Pequeño              780               1439
895    OUT960   57362.867709       Pequeño              660               1510
896    OUT535   61585.737092       Pequeño              990               1836
897    OUT202   95416.455607       Pequeño             1170               1500

[896 rows x 5 columns]